INSERT INTO PRJ_MENUITEM (NAME, URL, MENU_GROUP, MENU_ITEM_GROUP) VALUES ('ACTUATOR_APPLICATION', '/actuator/application', 'ADMINISTRATION', 'ACTUATOR');

INSERT INTO ACT_APPLICATION (NAME, URL) VALUES ('YQBoots Actuator', 'http://localhost:8080');
