INSERT INTO PRJ_MENUITEM (NAME, URL, MENU_GROUP, MENU_ITEM_GROUP) VALUES ('ACT_ACTUATOR', '/projects/actuator', 'PROJECTS', 'OPEN_SOURCE');

INSERT INTO ACT_APPLICATION (NAME, URL) VALUES ('YQBoots Actuator', 'http://localhost:8080');
